/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VideoGenRuntimeModule extends org.xtext.example.mydsl.AbstractVideoGenRuntimeModule {

}
