<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="playlist" nsURI="http://www.example.org/playlist" nsPrefix="playlist">
  <eClassifiers xsi:type="ecore:EClass" name="Playlist">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Content" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Content" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="#//Content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
