/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.m3U;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.playlist.m3u.m3U.M3UFactory
 * @model kind="package"
 * @generated
 */
public interface M3UPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "m3U";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.xtext.org/example/playlist/m3u/M3U";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "m3U";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  M3UPackage eINSTANCE = org.xtext.example.playlist.m3u.m3U.impl.M3UPackageImpl.init();

  /**
	 * The meta object id for the '{@link org.xtext.example.playlist.m3u.m3U.impl.ModelImpl <em>Model</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.example.playlist.m3u.m3U.impl.ModelImpl
	 * @see org.xtext.example.playlist.m3u.m3U.impl.M3UPackageImpl#getModel()
	 * @generated
	 */
  int MODEL = 0;

  /**
	 * The feature id for the '<em><b>List Video</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODEL__LIST_VIDEO = 0;

  /**
	 * The number of structural features of the '<em>Model</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODEL_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.example.playlist.m3u.m3U.impl.VideoImpl <em>Video</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.example.playlist.m3u.m3U.impl.VideoImpl
	 * @see org.xtext.example.playlist.m3u.m3U.impl.M3UPackageImpl#getVideo()
	 * @generated
	 */
  int VIDEO = 1;

  /**
	 * The feature id for the '<em><b>Location</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int VIDEO__LOCATION = 0;

  /**
	 * The number of structural features of the '<em>Video</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int VIDEO_FEATURE_COUNT = 1;


  /**
	 * Returns the meta object for class '{@link org.xtext.example.playlist.m3u.m3U.Model <em>Model</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Model</em>'.
	 * @see org.xtext.example.playlist.m3u.m3U.Model
	 * @generated
	 */
  EClass getModel();

  /**
	 * Returns the meta object for the containment reference list '{@link org.xtext.example.playlist.m3u.m3U.Model#getListVideo <em>List Video</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>List Video</em>'.
	 * @see org.xtext.example.playlist.m3u.m3U.Model#getListVideo()
	 * @see #getModel()
	 * @generated
	 */
  EReference getModel_ListVideo();

  /**
	 * Returns the meta object for class '{@link org.xtext.example.playlist.m3u.m3U.Video <em>Video</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Video</em>'.
	 * @see org.xtext.example.playlist.m3u.m3U.Video
	 * @generated
	 */
  EClass getVideo();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.example.playlist.m3u.m3U.Video#getLocation <em>Location</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Location</em>'.
	 * @see org.xtext.example.playlist.m3u.m3U.Video#getLocation()
	 * @see #getVideo()
	 * @generated
	 */
  EAttribute getVideo_Location();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  M3UFactory getM3UFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link org.xtext.example.playlist.m3u.m3U.impl.ModelImpl <em>Model</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.example.playlist.m3u.m3U.impl.ModelImpl
		 * @see org.xtext.example.playlist.m3u.m3U.impl.M3UPackageImpl#getModel()
		 * @generated
		 */
    EClass MODEL = eINSTANCE.getModel();

    /**
		 * The meta object literal for the '<em><b>List Video</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MODEL__LIST_VIDEO = eINSTANCE.getModel_ListVideo();

    /**
		 * The meta object literal for the '{@link org.xtext.example.playlist.m3u.m3U.impl.VideoImpl <em>Video</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.example.playlist.m3u.m3U.impl.VideoImpl
		 * @see org.xtext.example.playlist.m3u.m3U.impl.M3UPackageImpl#getVideo()
		 * @generated
		 */
    EClass VIDEO = eINSTANCE.getVideo();

    /**
		 * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute VIDEO__LOCATION = eINSTANCE.getVideo_Location();

  }

} //M3UPackage
