/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.playlist.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.playlist.Mediafile;
import org.xtext.example.mydsl.playlist.PlaylistFactory;
import org.xtext.example.mydsl.playlist.PlaylistGeneratorModel;
import org.xtext.example.mydsl.playlist.PlaylistPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PlaylistPackageImpl extends EPackageImpl implements PlaylistPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass playlistGeneratorModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mediafileEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.playlist.PlaylistPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private PlaylistPackageImpl()
  {
    super(eNS_URI, PlaylistFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link PlaylistPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static PlaylistPackage init()
  {
    if (isInited) return (PlaylistPackage)EPackage.Registry.INSTANCE.getEPackage(PlaylistPackage.eNS_URI);

    // Obtain or create and register package
    PlaylistPackageImpl thePlaylistPackage = (PlaylistPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof PlaylistPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new PlaylistPackageImpl());

    isInited = true;

    // Create package meta-data objects
    thePlaylistPackage.createPackageContents();

    // Initialize created meta-data
    thePlaylistPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePlaylistPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(PlaylistPackage.eNS_URI, thePlaylistPackage);
    return thePlaylistPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPlaylistGeneratorModel()
  {
    return playlistGeneratorModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPlaylistGeneratorModel_Mediafiles()
  {
    return (EReference)playlistGeneratorModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMediafile()
  {
    return mediafileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediafile_Id()
  {
    return (EAttribute)mediafileEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediafile_Location()
  {
    return (EAttribute)mediafileEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediafile_Duration()
  {
    return (EAttribute)mediafileEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PlaylistFactory getPlaylistFactory()
  {
    return (PlaylistFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    playlistGeneratorModelEClass = createEClass(PLAYLIST_GENERATOR_MODEL);
    createEReference(playlistGeneratorModelEClass, PLAYLIST_GENERATOR_MODEL__MEDIAFILES);

    mediafileEClass = createEClass(MEDIAFILE);
    createEAttribute(mediafileEClass, MEDIAFILE__ID);
    createEAttribute(mediafileEClass, MEDIAFILE__LOCATION);
    createEAttribute(mediafileEClass, MEDIAFILE__DURATION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(playlistGeneratorModelEClass, PlaylistGeneratorModel.class, "PlaylistGeneratorModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPlaylistGeneratorModel_Mediafiles(), this.getMediafile(), null, "mediafiles", null, 0, -1, PlaylistGeneratorModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mediafileEClass, Mediafile.class, "Mediafile", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMediafile_Id(), ecorePackage.getEString(), "id", null, 0, 1, Mediafile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMediafile_Location(), ecorePackage.getEString(), "location", null, 0, 1, Mediafile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMediafile_Duration(), ecorePackage.getEFloat(), "duration", null, 0, 1, Mediafile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //PlaylistPackageImpl
