/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.scoping;

import org.xtext.example.playlist.m3u.scoping.AbstractM3UScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class M3UScopeProvider extends AbstractM3UScopeProvider {
}
