/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractM3UValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.example.playlist.m3u.m3U.M3UPackage.eINSTANCE);
		return result;
	}
	
}
