/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.playlist.ide.contentassist.antlr.internal.InternalPlaylistParser;
import org.xtext.example.playlist.services.PlaylistGrammarAccess;

public class PlaylistParser extends AbstractContentAssistParser {

	@Inject
	private PlaylistGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalPlaylistParser createParser() {
		InternalPlaylistParser result = new InternalPlaylistParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVideoAccess().getGroup(), "rule__Video__Group__0");
					put(grammarAccess.getPlaylistAccess().getVideosAssignment(), "rule__Playlist__VideosAssignment");
					put(grammarAccess.getVideoAccess().getNameAssignment_1(), "rule__Video__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalPlaylistParser typedParser = (InternalPlaylistParser) parser;
			typedParser.entryRulePlaylist();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PlaylistGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlaylistGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
