/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.playlist.m3u.parser.antlr.internal.InternalM3UParser;
import org.xtext.example.playlist.m3u.services.M3UGrammarAccess;

public class M3UParser extends AbstractAntlrParser {

	@Inject
	private M3UGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalM3UParser createParser(XtextTokenStream stream) {
		return new InternalM3UParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public M3UGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(M3UGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
