/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.ui.contentassist;

import org.xtext.example.playlist.m3u.ui.contentassist.AbstractM3UProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class M3UProposalProvider extends AbstractM3UProposalProvider {
}
