/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u;

import org.xtext.example.playlist.m3u.AbstractM3URuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class M3URuntimeModule extends AbstractM3URuntimeModule {
}
