/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u;

import org.xtext.example.playlist.m3u.M3UStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class M3UStandaloneSetup extends M3UStandaloneSetupGenerated {
  public static void doSetup() {
    M3UStandaloneSetup _m3UStandaloneSetup = new M3UStandaloneSetup();
    _m3UStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
