version: '2'
services:
    lesnulseditiongenerator-app:
        image: lesnulseditiongenerator
        external_links:
            - lesnulseditiongenerator-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/lesnulseditiongenerator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lesnulseditiongenerator-mysql:
        extends:
            file: mysql.yml
            service: lesnulseditiongenerator-mysql
