version: '2'
services:
    lesnulseditiongenerator-sonar:
        container_name: lesnulseditiongenerator-sonar
        image: sonarqube:6.1-alpine
        ports:
            - 9000:9000
            - 9092:9092
