version: '2'
services:
    videogenwebsite-mysql:
        container_name: videogenwebsite-mysql
        image: mysql:5.7.15
        # volumes:
        #     - ~/volumes/jhipster/VideoGenWebSite/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=videogenwebsite
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
