/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractM3UScopeProvider extends DelegatingScopeProvider {
}
