version: '2'
services:
    videogenapp-app:
        image: videogenapp
        external_links:
            - videogenapp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/videogenapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    videogenapp-mysql:
        extends:
            file: mysql.yml
            service: videogenapp-mysql
