/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.ui;

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PlaylistUiModule /* implements AbstractPlaylistUiModule  */{
}
