version: '2'
services:
    videogenapplication-app:
        image: videogenapplication
        external_links:
            - videogenapplication-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/videogenapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    videogenapplication-mysql:
        extends:
            file: mysql.yml
            service: videogenapplication-mysql
