/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.playlist.m3u.ui.AbstractM3UUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class M3UUiModule extends AbstractM3UUiModule {
  public M3UUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
