/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.playlist;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.playlist.PlaylistFactory
 * @model kind="package"
 * @generated
 */
public interface PlaylistPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "playlist";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Playlist";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "playlist";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PlaylistPackage eINSTANCE = org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.playlist.impl.PlaylistImpl <em>Playlist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.playlist.impl.PlaylistImpl
   * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getPlaylist()
   * @generated
   */
  int PLAYLIST = 0;

  /**
   * The feature id for the '<em><b>Vids</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYLIST__VIDS = 0;

  /**
   * The number of structural features of the '<em>Playlist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYLIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.playlist.impl.MediaFileImpl <em>Media File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.playlist.impl.MediaFileImpl
   * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getMediaFile()
   * @generated
   */
  int MEDIA_FILE = 1;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_FILE__LOCATION = 0;

  /**
   * The number of structural features of the '<em>Media File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_FILE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.playlist.Playlist <em>Playlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Playlist</em>'.
   * @see org.xtext.example.mydsl.playlist.Playlist
   * @generated
   */
  EClass getPlaylist();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.playlist.Playlist#getVids <em>Vids</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vids</em>'.
   * @see org.xtext.example.mydsl.playlist.Playlist#getVids()
   * @see #getPlaylist()
   * @generated
   */
  EReference getPlaylist_Vids();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.playlist.MediaFile <em>Media File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Media File</em>'.
   * @see org.xtext.example.mydsl.playlist.MediaFile
   * @generated
   */
  EClass getMediaFile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.playlist.MediaFile#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.xtext.example.mydsl.playlist.MediaFile#getLocation()
   * @see #getMediaFile()
   * @generated
   */
  EAttribute getMediaFile_Location();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PlaylistFactory getPlaylistFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.playlist.impl.PlaylistImpl <em>Playlist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.playlist.impl.PlaylistImpl
     * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getPlaylist()
     * @generated
     */
    EClass PLAYLIST = eINSTANCE.getPlaylist();

    /**
     * The meta object literal for the '<em><b>Vids</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLAYLIST__VIDS = eINSTANCE.getPlaylist_Vids();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.playlist.impl.MediaFileImpl <em>Media File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.playlist.impl.MediaFileImpl
     * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getMediaFile()
     * @generated
     */
    EClass MEDIA_FILE = eINSTANCE.getMediaFile();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIA_FILE__LOCATION = eINSTANCE.getMediaFile_Location();

  }

} //PlaylistPackage
