/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class M3URuntimeModule extends AbstractM3URuntimeModule {
}
