/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class M3UStandaloneSetup extends M3UStandaloneSetupGenerated {

	def static void doSetup() {
		new M3UStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
