/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.playlist.m3u.ui.internal.M3uActivator;

public class M3UUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return M3uActivator.getInstance().getInjector("org.xtext.example.playlist.m3u.M3U");
	}

}
