/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.playlist.m3u.ui.internal.M3uActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class M3UExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return M3uActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return M3uActivator.getInstance().getInjector(M3uActivator.ORG_XTEXT_EXAMPLE_PLAYLIST_M3U_M3U);
	}
	
}
