/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.playlist;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.playlist.PlaylistFactory
 * @model kind="package"
 * @generated
 */
public interface PlaylistPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "playlist";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Playlist";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "playlist";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PlaylistPackage eINSTANCE = org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.playlist.impl.PlaylistGeneratorModelImpl <em>Generator Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.playlist.impl.PlaylistGeneratorModelImpl
   * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getPlaylistGeneratorModel()
   * @generated
   */
  int PLAYLIST_GENERATOR_MODEL = 0;

  /**
   * The feature id for the '<em><b>Mediafiles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYLIST_GENERATOR_MODEL__MEDIAFILES = 0;

  /**
   * The number of structural features of the '<em>Generator Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLAYLIST_GENERATOR_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.playlist.impl.MediafileImpl <em>Mediafile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.playlist.impl.MediafileImpl
   * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getMediafile()
   * @generated
   */
  int MEDIAFILE = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIAFILE__ID = 0;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIAFILE__LOCATION = 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIAFILE__DURATION = 2;

  /**
   * The number of structural features of the '<em>Mediafile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIAFILE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.playlist.PlaylistGeneratorModel <em>Generator Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Generator Model</em>'.
   * @see org.xtext.example.mydsl.playlist.PlaylistGeneratorModel
   * @generated
   */
  EClass getPlaylistGeneratorModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.playlist.PlaylistGeneratorModel#getMediafiles <em>Mediafiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mediafiles</em>'.
   * @see org.xtext.example.mydsl.playlist.PlaylistGeneratorModel#getMediafiles()
   * @see #getPlaylistGeneratorModel()
   * @generated
   */
  EReference getPlaylistGeneratorModel_Mediafiles();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.playlist.Mediafile <em>Mediafile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mediafile</em>'.
   * @see org.xtext.example.mydsl.playlist.Mediafile
   * @generated
   */
  EClass getMediafile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.playlist.Mediafile#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.playlist.Mediafile#getId()
   * @see #getMediafile()
   * @generated
   */
  EAttribute getMediafile_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.playlist.Mediafile#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.xtext.example.mydsl.playlist.Mediafile#getLocation()
   * @see #getMediafile()
   * @generated
   */
  EAttribute getMediafile_Location();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.playlist.Mediafile#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.mydsl.playlist.Mediafile#getDuration()
   * @see #getMediafile()
   * @generated
   */
  EAttribute getMediafile_Duration();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PlaylistFactory getPlaylistFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.playlist.impl.PlaylistGeneratorModelImpl <em>Generator Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.playlist.impl.PlaylistGeneratorModelImpl
     * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getPlaylistGeneratorModel()
     * @generated
     */
    EClass PLAYLIST_GENERATOR_MODEL = eINSTANCE.getPlaylistGeneratorModel();

    /**
     * The meta object literal for the '<em><b>Mediafiles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLAYLIST_GENERATOR_MODEL__MEDIAFILES = eINSTANCE.getPlaylistGeneratorModel_Mediafiles();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.playlist.impl.MediafileImpl <em>Mediafile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.playlist.impl.MediafileImpl
     * @see org.xtext.example.mydsl.playlist.impl.PlaylistPackageImpl#getMediafile()
     * @generated
     */
    EClass MEDIAFILE = eINSTANCE.getMediafile();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIAFILE__ID = eINSTANCE.getMediafile_Id();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIAFILE__LOCATION = eINSTANCE.getMediafile_Location();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIAFILE__DURATION = eINSTANCE.getMediafile_Duration();

  }

} //PlaylistPackage
