/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.playlist;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generator Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.playlist.PlaylistGeneratorModel#getMediafiles <em>Mediafiles</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.playlist.PlaylistPackage#getPlaylistGeneratorModel()
 * @model
 * @generated
 */
public interface PlaylistGeneratorModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Mediafiles</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.playlist.Mediafile}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mediafiles</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mediafiles</em>' containment reference list.
   * @see org.xtext.example.mydsl.playlist.PlaylistPackage#getPlaylistGeneratorModel_Mediafiles()
   * @model containment="true"
   * @generated
   */
  EList<Mediafile> getMediafiles();

} // PlaylistGeneratorModel
