/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.m3u.validation;

import org.xtext.example.playlist.m3u.validation.AbstractM3UValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class M3UValidator extends AbstractM3UValidator {
}
