/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.example.mydsl.tests.PlaylistInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(PlaylistInjectorProvider.class)
@SuppressWarnings("all")
public class PlaylistParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field PlaylistParsingTest.parseHelper refers to the missing type Model");
  }
}
