/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist;

import org.xtext.example.mydsl.AbstractPlaylistRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlaylistRuntimeModule extends AbstractPlaylistRuntimeModule {
}
