/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist;

import org.xtext.example.playlist.PlaylistStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PlaylistStandaloneSetup extends PlaylistStandaloneSetupGenerated {
  public static void doSetup() {
    PlaylistStandaloneSetup _playlistStandaloneSetup = new PlaylistStandaloneSetup();
    _playlistStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
