/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.playlist.parser.antlr.internal.InternalPlaylistParser;
import org.xtext.example.playlist.services.PlaylistGrammarAccess;

public class PlaylistParser extends AbstractAntlrParser {

	@Inject
	private PlaylistGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPlaylistParser createParser(XtextTokenStream stream) {
		return new InternalPlaylistParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Playlist";
	}

	public PlaylistGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlaylistGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
