/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.playlist.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PlaylistAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/playlist/parser/antlr/internal/InternalPlaylist.tokens");
	}
}
